/**
 * ArchitecturePage — solution architecture diagram (Mermaid) + component inventory.
 */
import React, { useEffect, useRef } from 'react';
import { Grid, Column, Tile, Tag } from '@carbon/react';
import { StructuredList, StructuredListHead, StructuredListRow, StructuredListCell, StructuredListBody } from '@carbon/react';

const MERMAID_DIAGRAM = `
graph TB
  subgraph Client["Client Layer"]
    UI["Carbon React UI\\n(IBM Design System v11)"]
  end

  subgraph API["API Gateway"]
    GW["FastAPI Backend\\n(Port 8000)"]
  end

  subgraph AI["IBM watsonx Platform"]
    WX["watsonx.ai\\nmeta-llama/llama-4-maverick-17b"]
    GT["IBM Granite Models\\nFallback / IBM-brand story"]
  end

  subgraph Agent["AI Agent Layer"]
    LA["LangGraph ReAct Agent\\nIoT Analysis Pipeline"]
    AD["Anomaly Detection\\nThreshold Engine"]
    FP["Failure Prediction\\nML Trend Analysis"]
    WO["Work Order Generator\\nParts + Technician Match"]
  end

  subgraph Data["Data Layer"]
    SY["Synthetic IoT Data\\nFaker seed=42, 120 assets"]
    DB["In-Memory Data Store\\nFleet + Work Orders"]
  end

  subgraph IoT["IoT Sensor Layer"]
    SN["240+ Sensors/Asset\\nVibration · Temp · Current\\nPressure · Oil · Noise"]
  end

  subgraph Ops["Observability"]
    IN["Instana APM\\n(Future integration)"]
    LOG["FastAPI Logs\\nUvicorn structured"]
  end

  UI -->|REST API calls| GW
  GW --> LA
  LA --> AD
  LA --> FP
  LA --> WO
  LA -->|Inference| WX
  WX -.->|Fallback| GT
  AD --> DB
  FP --> DB
  WO --> DB
  SN --> SY
  SY --> DB
  GW -.->|Metrics| IN
  GW --> LOG

  style WX fill:#0f62fe,color:#fff
  style GT fill:#0f62fe,color:#fff
  style LA fill:#6929c4,color:#fff
  style UI fill:#262626,color:#f4f4f4
`;

const COMPONENTS = [
  { component: 'Carbon React UI', version: 'v11.73', role: 'Demo frontend — 5 pages: Dashboard, Problem, AI Agent, Results, Architecture', layer: 'Frontend' },
  { component: 'FastAPI', version: '0.115.0', role: 'REST API backend, CORS, dual-mode (mock/live)', layer: 'Backend' },
  { component: 'LangGraph ReAct Agent', version: '≥0.2.0', role: 'AI agent pipeline: anomaly detection → failure prediction → work order generation', layer: 'AI Agent' },
  { component: 'ibm-watsonx-ai SDK', version: '≥1.1.0', role: 'watsonx.ai model inference (live mode)', layer: 'IBM Platform' },
  { component: 'watsonx.ai (Llama 4 Maverick)', version: 'meta-llama/llama-4-maverick-17b-128e-instruct-fp8', role: 'Default LLM — multimodal text+vision', layer: 'IBM Platform' },
  { component: 'IBM Granite Models', version: 'ibm/granite-3-3-8b-instruct', role: 'IBM-brand story fallback model', layer: 'IBM Platform' },
  { component: 'Synthetic Data Service', version: 'Faker 30.8, seed=42', role: '120 synthetic equipment assets, 500 sensor readings, 30 work orders', layer: 'Data' },
  { component: 'Carbon Charts React', version: '1.20.0', role: 'Area, Donut, Bar, Line charts — g90 dark theme', layer: 'Frontend' },
  { component: 'Docker / UBI 9', version: 'DEPLOY_TARGET=openshift', role: 'Container packaging for OpenShift deployment', layer: 'Infra' },
];

export default function ArchitecturePage() {
  const diagramRef = useRef(null);

  useEffect(() => {
    (async () => {
      try {
        const { default: mermaid } = await import('mermaid');
        mermaid.initialize({ startOnLoad: false, theme: 'dark', securityLevel: 'loose' });
        const { svg } = await mermaid.render('arch-diagram', MERMAID_DIAGRAM.trim());
        if (diagramRef.current) {
          // Safe SVG: generated by mermaid from our own static string, no user input
          diagramRef.current.innerHTML = svg;
        }
      } catch (e) {
        console.error('Mermaid render error:', e);
      }
    })();
  }, []);

  return (
    <div>
      <h1 style={{ marginBottom: '0.5rem', fontSize: '1.75rem', fontWeight: 600 }}>Solution Architecture</h1>
      <p style={{ color: '#a8a8a8', marginBottom: '2rem', fontSize: '0.875rem' }}>
        IBM watsonx Predictive Maintenance — end-to-end architecture for DEMO-MFG-001.
      </p>

      {/* Mermaid diagram */}
      <Tile style={{ background: '#1c1c1c', padding: '1.5rem', marginBottom: '2rem', overflowX: 'auto' }}>
        <h3 style={{ marginBottom: '1rem', fontSize: '1rem', fontWeight: 600 }}>System Architecture</h3>
        <div ref={diagramRef} aria-label="Architecture diagram" role="img" style={{ minHeight: '400px' }} />
      </Tile>

      {/* Component inventory */}
      <Tile style={{ background: '#262626', padding: '1.5rem' }}>
        <h3 style={{ marginBottom: '1rem', fontSize: '1rem', fontWeight: 600 }}>Component Inventory</h3>
        <StructuredList>
          <StructuredListHead>
            <StructuredListRow head>
              <StructuredListCell head>Component</StructuredListCell>
              <StructuredListCell head>Version / ID</StructuredListCell>
              <StructuredListCell head>Role</StructuredListCell>
              <StructuredListCell head>Layer</StructuredListCell>
            </StructuredListRow>
          </StructuredListHead>
          <StructuredListBody>
            {COMPONENTS.map((c) => (
              <StructuredListRow key={c.component}>
                <StructuredListCell noWrap>{c.component}</StructuredListCell>
                <StructuredListCell>
                  <code style={{ fontSize: '0.75rem', color: '#78a9ff' }}>{c.version}</code>
                </StructuredListCell>
                <StructuredListCell>{c.role}</StructuredListCell>
                <StructuredListCell>
                  <Tag type={
                    c.layer === 'IBM Platform' ? 'blue' :
                    c.layer === 'AI Agent' ? 'purple' :
                    c.layer === 'Frontend' ? 'teal' :
                    c.layer === 'Backend' ? 'cyan' :
                    c.layer === 'Data' ? 'warm-gray' : 'gray'
                  } size="sm">{c.layer}</Tag>
                </StructuredListCell>
              </StructuredListRow>
            ))}
          </StructuredListBody>
        </StructuredList>
      </Tile>
    </div>
  );
}
